name: Build and publish new version of @intersect.mbo/pdf-ui package
run-name: Publish by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pdf-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          scope: "@intersect.mbo"

      - name: Authenticate with Scoped NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          registry-url: "https://registry.npmjs.org"
          scope: "@intersect.mbo"
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm config set scope "@intersect.mbo"
          npm whoami

      - name: Check NPM Authentication
        run: npm whoami

      - name: Install dependencies
        run: npm ci
        env:
          NODE_OPTIONS: --max_old_space_size=8192

      - name: Publish to npm
        run: npm publish --access restricted
        env:
          NODE_OPTIONS: --max_old_space_size=8192
